{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sits
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sits_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sits/sits_{{ version }}.tar.gz
  sha256: b3f0fedf0c738fbf64ea6980d6d82d89d4f058dbb0881caa62641b2b69fd9bf9

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-data.table >=1.13
    - r-dplyr >=1.0.0
    - r-gdalutilities
    - r-ggplot2
    - r-lubridate
    - r-magrittr
    - r-purrr >=0.3.0
    - r-rstac >=0.9.1_5
    - r-sf >=1.0
    - r-slider >=0.2.0
    - r-terra >=1.5_17
    - r-tibble >=3.1
    - r-tidyr >=1.2.0
    - r-torch >=0.7.0
    - r-yaml
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcpparmadillo
    - r-data.table >=1.13
    - r-dplyr >=1.0.0
    - r-gdalutilities
    - r-ggplot2
    - r-lubridate
    - r-magrittr
    - r-purrr >=0.3.0
    - r-rstac >=0.9.1_5
    - r-sf >=1.0
    - r-slider >=0.2.0
    - r-terra >=1.5_17
    - r-tibble >=3.1
    - r-tidyr >=1.2.0
    - r-torch >=0.7.0
    - r-yaml

test:
  commands:
    - $R -e "library('sits')"           # [not win]
    - "\"%R%\" -e \"library('sits')\""  # [win]

about:
  home: https://github.com/e-sensing/sits/, https://e-sensing.github.io/sitsbook/
  license: GPL-2.0-or-later
  summary: 'An end-to-end toolkit for land use and land cover classification using big Earth
    observation data, based on machine learning methods applied to satellite image data
    cubes, as described in Simoes et al (2021) <doi:10.3390/rs13132428>. Builds regular
    data cubes from collections in AWS, Microsoft Planetary Computer, Brazil Data Cube,
    and Digital Earth Africa using the STAC protocol <https://stacspec.org/> and the
    ''gdalcubes'' R package <doi:10.3390/data4030092>. Supports visualization methods
    for images and time series and smoothing filters for dealing with noisy time series.
    Includes functions for quality assessment of training samples using self-organized
    maps as presented by Santos et al (2021) <doi:10.1016/j.isprsjprs.2021.04.014>.
    Provides machine learning methods including support vector machines, random forests,
    extreme gradient boosting, multi-layer perceptrons, temporal convolutional neural
    networks <doi:10.3390/rs11050523>, residual networks <arxiv:1809.04356>, and temporal
    attention encoders <arXiv:2007.00586>. Performs efficient classification of big
    Earth observation data cubes and includes functions for post-classification smoothing
    based on Bayesian inference, and methods for uncertainty assessment. Enables best
    practices for estimating area and assessing accuracy of land change as recommended
    by Olofsson et al(2014) <doi:10.1016/j.rse.2014.02.015>. Minimum recommended requirements:
    16 GB RAM and 4 CPU dual-core.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - TomAugspurger

# Package: sits
# Type: Package
# Version: 1.0.0
# Title: Satellite Image Time Series Analysis for Earth Observation Data Cubes
# Authors@R: c(person('Rolf', 'Simoes', role = c('aut'), email = 'rolf.simoes@inpe.br'), person('Gilberto', 'Camara', role = c('aut', 'cre'), email = 'gilberto.camara.inpe@gmail.com'), person('Felipe', 'Souza', role = c('aut'), email = 'felipe.carvalho@inpe.br'), person('Lorena', 'Santos', role = c('aut'), email = 'lorena.santos@inpe.br'), person('Pedro', 'Andrade', role = c('aut'), email = 'pedro.andrade@inpe.br'), person('Karine', 'Ferreira', role = c('aut'), email = 'karine.ferreira@inpe.br'), person('Alber', 'Sanchez', role = c('aut'), email = 'alber.ipia@inpe.br'), person('Gilberto', 'Queiroz', role = c('aut'), email = 'gilberto.queiroz@inpe.br') )
# Maintainer: Gilberto Camara <gilberto.camara.inpe@gmail.com>
# Description: An end-to-end toolkit for land use and land cover classification using big Earth observation data, based on machine learning methods applied to satellite image data cubes, as described in Simoes et al (2021) <doi:10.3390/rs13132428>. Builds regular data cubes from collections in AWS, Microsoft Planetary Computer, Brazil Data Cube, and Digital Earth Africa using the STAC protocol <https://stacspec.org/> and the 'gdalcubes' R package <doi:10.3390/data4030092>. Supports visualization methods for images and time series and smoothing filters for dealing with noisy time series. Includes functions for quality assessment of training samples using self-organized maps as presented by Santos et al (2021) <doi:10.1016/j.isprsjprs.2021.04.014>. Provides machine learning methods including support vector machines, random forests, extreme gradient boosting, multi-layer perceptrons, temporal convolutional neural networks <doi:10.3390/rs11050523>, residual networks <arxiv:1809.04356>, and temporal attention encoders <arXiv:2007.00586>. Performs efficient classification of big Earth observation data cubes and includes functions for post-classification smoothing based on Bayesian inference, and methods for uncertainty assessment. Enables best practices for estimating area and assessing accuracy of land change as recommended by Olofsson et al(2014) <doi:10.1016/j.rse.2014.02.015>. Minimum recommended requirements: 16 GB RAM and 4 CPU dual-core.
# Encoding: UTF-8
# Language: en-US
# Depends: R (>= 4.0.0)
# URL: https://github.com/e-sensing/sits/, https://e-sensing.github.io/sitsbook/
# BugReports: https://github.com/e-sensing/sits/issues
# License: GPL-2
# ByteCompile: true
# LazyData: true
# Imports: magrittr, yaml, data.table (>= 1.13), dplyr (>= 1.0.0), gdalUtilities, grDevices, ggplot2, graphics, lubridate, parallel (>= 4.0.5), purrr (>= 0.3.0), Rcpp, rstac (>= 0.9.1-5), sf (>= 1.0), slider (>= 0.2.0), stats, terra (>= 1.5-17), tibble (>= 3.1), tidyr (>= 1.2.0), torch (>= 0.7.0), utils
# Suggests: caret, dendextend, dtwclust, dtwSat (>= 0.2.7), digest, e1071, FNN, gdalcubes (>= 0.6.0), geojsonsf, httr, jsonlite, kohonen(>= 3.0.11), leafem (>= 0.2.0), leaflet (>= 2.1.1), luz (>= 0.2.0), methods, mgcv, openxlsx, randomForest, RcppArmadillo (>= 0.11), scales, stars (>= 0.5), testthat (>= 3.1.3), torchopt(>= 0.1.1), xgboost, zoo
# Config/testthat/edition: 3
# Config/testthat/parallel: false
# Config/testthat/start-first: cube, raster, ml
# LinkingTo: Rcpp, RcppArmadillo
# RoxygenNote: 7.2.0
# Collate: 'RcppExports.R' 'data.R' 'pipe.R' 'sits-package.R' 'sits_apply.R' 'sits_accuracy.R' 'sits_active_learning.R' 'sits_bands.R' 'sits_bbox.R' 'sits_classification.R' 'sits_classify_ts.R' 'sits_classify_cube.R' 'sits_compare.R' 'sits_config.R' 'sits_csv.R' 'sits_cube.R' 'sits_cube_aux_functions.R' 'sits_check.R' 'sits_cluster.R' 'sits_debug.R' 'sits_distances.R' 'sits_dt_reference.R' 'sits_factory.R' 'sits_file_info.R' 'sits_filters.R' 'sits_gdalcubes.R' 'sits_geo_dist.R' 'sits_get_data.R' 'sits_imputation.R' 'sits_labels.R' 'sits_label_classification.R' 'sits_lighttae.R' 'sits_machine_learning.R' 'sits_merge.R' 'sits_mlp.R' 'sits_parallel.R' 'sits_patterns.R' 'sits_plot.R' 'sits_raster_api.R' 'sits_raster_api_terra.R' 'sits_raster_blocks.R' 'sits_raster_data.R' 'sits_raster_sub_image.R' 'sits_regularize.R' 'sits_resnet.R' 'sits_roi.R' 'sits_sample_functions.R' 'sits_select.R' 'sits_sf.R' 'sits_shp.R' 'sits_smooth.R' 'sits_smooth_aux_functions.R' 'sits_som.R' 'sits_source_api.R' 'sits_source_api_aws.R' 'sits_source_api_bdc.R' 'sits_source_api_deafrica.R' 'sits_source_api_local.R' 'sits_source_api_mspc.R' 'sits_source_api_stac.R' 'sits_source_api_usgs.R' 'sits_space_time_operations.R' 'sits_stac.R' 'sits_tae.R' 'sits_tempcnn.R' 'sits_torch_conv1d.R' 'sits_torch_linear.R' 'sits_torch_spatial_encoder.R' 'sits_torch_temporal_attention_encoder.R' 'sits_tibble.R' 'sits_timeline.R' 'sits_train.R' 'sits_tuning.R' 'sits_twdtw.R' 'sits_utils.R' 'sits_uncertainty.R' 'sits_validate.R' 'sits_view.R' 'sits_values.R' 'sits_xlsx.R' 'zzz.R'
# NeedsCompilation: yes
# Packaged: 2022-05-19 00:09:17 UTC; gilbertocamara
# Author: Rolf Simoes [aut], Gilberto Camara [aut, cre], Felipe Souza [aut], Lorena Santos [aut], Pedro Andrade [aut], Karine Ferreira [aut], Alber Sanchez [aut], Gilberto Queiroz [aut]
# Repository: CRAN
# Date/Publication: 2022-05-19 07:00:02 UTC
