{% set version = "1.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sits
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sits_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sits/sits_{{ version }}.tar.gz
  sha256: 3c5d9ed930990d7b3a34baa1f8f7b0f9d6447bb159f6cfb4fcd8aafc51581c4c

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - _openmp_mutex                # [linux]
    - llvm-openmp                  # [osx]
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-dplyr >=1.0.0
    - r-gdalutilities
    - r-lubridate
    - r-purrr >=1.0.2
    - r-rstac >=0.9.2_5
    - r-sf >=1.0_12
    - r-showtext
    - r-slider >=0.2.0
    - r-sysfonts
    - r-terra >=1.5_17
    - r-tibble >=3.1
    - r-tidyr >=1.2.0
    - r-torch >=0.11.0
    - r-yaml
  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-dplyr >=1.0.0
    - r-gdalutilities
    - r-lubridate
    - r-purrr >=1.0.2
    - r-rstac >=0.9.2_5
    - r-sf >=1.0_12
    - r-showtext
    - r-slider >=0.2.0
    - r-sysfonts
    - r-terra >=1.5_17
    - r-tibble >=3.1
    - r-tidyr >=1.2.0
    - r-torch >=0.11.0
    - r-yaml

test:
  commands:
    - $R -e "library('sits')"           # [not win]
    - "\"%R%\" -e \"library('sits')\""  # [win]

about:
  home: https://github.com/e-sensing/sits
  license: GPL-2.0-only
  summary: |
    The sits R package provides a set of tools for analysis, visualization and classification of satellite image time series. The main aim of SITS is to support land cover and land change classification of image data cubes using machine learning methods. The basic workflow in SITS is:

    1. Create a data cube using image collections available in the cloud or in local machines.
    2. Extract time series from the data cube which are used as training data.
    3. Perform quality control and filtering on the samples.
    4. Train a machine learning model using the extracted samples.
    5. Classify the data cube using the trained model.
    6. Post-process the classified images.
    7. Evaluate the accuracy of the classification using best practices.

  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - TomAugspurger
