{% set version = "1.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sits
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/e-sensing/sits/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ae95a89d953125497edb938e6de10c49b9210d6db344eea473b5f69c5ac36247

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - _openmp_mutex                # [linux]
    - llvm-openmp                  # [osx]
    - r-base
    - r-dplyr >=1.0.0
    - r-gdalutilities
    - r-lubridate
    - r-magrittr
    - r-purrr >=0.3.0
    - r-rcpp
    - r-rcpparmadillo >=0.11
    - r-rstac >=0.9.2_2
    - r-sf >=1.0
    - r-slider >=0.2.0
    - r-terra >=1.5.17
    - r-tibble >=3.1
    - r-tidyr >=1.2.0
    - r-torch >=0.9.0
    - r-yaml
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-gdalutilities
    - r-lubridate
    - r-magrittr
    - r-purrr >=0.3.0
    - r-rcpp
    - r-rcpparmadillo >=0.11
    - r-rstac >=0.9.2_2
    - r-sf >=1.0
    - r-slider >=0.2.0
    - r-terra >=1.5.17
    - r-tibble >=3.1
    - r-tidyr >=1.2.0
    - r-torch >=0.9.0
    - r-yaml

test:
  commands:
    - $R -e "library('sits')"           # [not win]
    - "\"%R%\" -e \"library('sits')\""  # [win]

about:
  home: https://github.com/e-sensing/sits
  license: GPL-3.0-or-later
  summary: |
    The sits R package provides a set of tools for analysis, visualization and classification of satellite image time series. The main aim of SITS is to support land cover and land change classification of image data cubes using machine learning methods. The basic workflow in SITS is:

    1. Create a data cube using image collections available in the cloud or in local machines.
    2. Extract time series from the data cube which are used as training data.
    3. Perform quality control and filtering on the samples.
    4. Train a machine learning model using the extracted samples.
    5. Classify the data cube using the trained model.
    6. Post-process the classified images.
    7. Evaluate the accuracy of the classification using best practices.

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - TomAugspurger
